import Title from "./components/Title";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";


export const metadata = {
  title: "AnimeCom",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    
      <body>
      <Title />
      {children}
      </body>

  );
}
